server:
  host: 0.0.0.0
  port: 6379
  metrics_port: 2112
  http_port: 8080

storage:
  cleanup_interval_seconds: 60
  max_memory_mb: 512
  snapshot_file: "./data/dump.json"
  snapshot_interval_seconds: 30